import Link from "next/link";

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-page text-ink-100">
      <div className="mx-auto max-w-2xl px-4 pb-20 pt-12 md:px-6 md:pt-16">
        <p className="text-sm text-ink-400">
          <Link
            href="/"
            className="text-accent-muted transition-colors hover:text-ink-100"
          >
            ← Back
          </Link>
        </p>
        <h1 className="mt-8 font-display text-3xl font-semibold text-ink-100">
          Legal
        </h1>
        <p className="mt-2 text-sm text-ink-500">
          Terms, privacy, and disclaimer for WhatAptIsThis.
        </p>

        <section className="mt-12">
          <h2 className="font-display text-xl font-semibold text-ink-100">
            Terms of Service
          </h2>
          <ul className="mt-4 list-disc space-y-3 pl-5 text-sm leading-relaxed text-ink-300">
            <li>
              WhatAptIsThis provides AI-powered apartment identification as an
              informational tool only.
            </li>
            <li>
              Results are AI-generated estimates and not guaranteed to be
              accurate.
            </li>
            <li>
              We are not a real estate broker, agent, or locator service.
            </li>
            <li>
              We do not guarantee the accuracy, completeness, or reliability of
              any results.
            </li>
            <li>
              Users should independently verify all apartment information before
              making any decisions.
            </li>
            <li>
              All purchases are final and non-refundable once scan credits are
              used.
            </li>
            <li>Unused scan credits do not expire.</li>
            <li>
              We reserve the right to modify pricing and features at any time.
            </li>
            <li>
              Abuse of the service (botting, scraping, reselling results) will
              result in account termination.
            </li>
            <li>You must be 18 or older to purchase credits.</li>
          </ul>
        </section>

        <section className="mt-14">
          <h2 className="font-display text-xl font-semibold text-ink-100">
            Privacy Policy
          </h2>
          <ul className="mt-4 list-disc space-y-3 pl-5 text-sm leading-relaxed text-ink-300">
            <li>
              We collect: IP address (for rate limiting and credit tracking),
              email address (only if you make a purchase, provided by Stripe),
              TikTok/Instagram URLs you submit for scanning.
            </li>
            <li>
              We do not sell or share your personal information with third
              parties.
            </li>
            <li>
              We use cookies and browser identifiers for rate limiting purposes.
            </li>
            <li>
              Scan results and submitted URLs are stored to improve our service.
            </li>
            <li>
              Payment processing is handled by Stripe — we never see or store
              your full card details.
            </li>
            <li>
              You can request deletion of your data by contacting us at{" "}
              <span className="text-ink-400">[add email later]</span>.
            </li>
            <li>
              We use third-party AI services (Google, OpenRouter) to process
              scans — submitted video frames are sent to these services for
              analysis.
            </li>
          </ul>
        </section>

        <section className="mt-14">
          <h2 className="font-display text-xl font-semibold text-ink-100">
            Disclaimer
          </h2>
          <ul className="mt-4 list-disc space-y-3 pl-5 text-sm leading-relaxed text-ink-300">
            <li>
              WhatAptIsThis is not affiliated with any apartment complex, real
              estate agency, or listing platform.
            </li>
            <li>Results are generated by AI and may be incorrect.</li>
            <li>
              We are not responsible for any decisions made based on our
              results.
            </li>
            <li>
              Apartment availability, pricing, and promotions change frequently
              — always verify directly with the property.
            </li>
          </ul>
        </section>
      </div>
    </div>
  );
}
